### ISSUE TITLE
Full build environment in GIT

### ISSUE THREAD

**Issue by HakanL** [hhromic/libe131#1]
It would be great if you could have the full build environment in the GIT repository, so I could clone the repo and do the configure and make.

**Comment by hhromic** [comment]
Hi @HakanL ,

I'm very sorry for the very late reply to your issue. I didn't have time to check it out when I received the message and then it simply slipped-out of my mind. Apologies.
Regarding your issue, it is not recommended to version the full build environment in Git or SVN because those files are usually local and tend to generate a lot of merging headaches. You can [check here for an interesting debate](https://stackoverflow.com/q/893913).

For the above reason, I provided the `autogen.sh` helper script that will generate the build environment for you after you check-out the repository. Hence, the proper way to use should be:

    $ git clone https://github.com/hhromic/libe131/
    $ cd libe131
    $ ./autogen.sh   # will generate autoconf files, just needed once
    $ ./configure --prefix=/usr
    $ make
    $ make install

Sorry again for the long delay answering this!
Hugo.

**Comment by HakanL** [comment]
Yea that makes sense, I can't remember what my issue was now, but let me try it again :)
